"""add phone number

Revision ID: 21cf15cf5652
Revises: 95e708596a08
Create Date: 2023-04-20 18:26:59.153699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cf15cf5652'
down_revision = '95e708596a08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'phone_number')
    # ### end Alembic commands ###
